[package]
name = "lucien"
description = "A rust cli application to fix ebook metadata"
version = "0.1.0"
edition = "2024"

[dependencies]
config = "0.15.15"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
mockall = "0.13.1"
